name: Build containers

on:
  pull_request:
    # Only consider PRs that change files for this asset, including ci scripts.
    paths:
      - ".github/workflows/containers.yaml"
      - "Tre-Harusa/**"
      - "Tre-SQL-PG/**"
      - "Tre-SQL-Trino/**"
  push:
    # Only release off of release and maintenance branches for this asset
    branches:
      - "main"
    # Only consider pushes that change files for this asset, including ci scripts
    paths:
      - ".github/workflows/containers.yaml"
      - "Tre-Harusa/**"
      - "Tre-SQL-PG/**"
      - "Tre-SQL-Trino/**"
permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Job name must be unique across repo to target
  # branch protection rules "required checks" properly!
  containers:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-repo.yaml@v2.0.1-repo
    with:
      job-name: containers
      release-tag-format: "v${version}-containers"

  tre-hasura-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.1.0-bulk-containers
    with:
      job-name: tre-hasura-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-hasura
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: Tre-Hasura/Dockerfile
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  tre-sql-pg-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.1.0-bulk-containers
    with:
      job-name: tre-sql-pg-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-sqlpg
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: Tre-SQL-PG/Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  tre-sql-trino-container:
    needs: containers
    uses: SwanseaUniversityMedical/workflows/.github/workflows/bulk-pr-and-release-container.yaml@v1.1.0-bulk-containers
    with:
      job-name: tre-sql-trino-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: ${{ vars.HARBOR_PROJECT }}/${{ vars.HARBOR_REPO }}-tre-sqltrino
      release-info: ${{ needs.containers.outputs.release-info }}
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: Tre-SQL-Trino/Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
